vagrantfile:
    synced_folder:
        # vflnp_ko67:
        #     source: ./www
        #     target: /var/www/local
        # lklkoko:
        #     source: ./www111
        #     target: /var/www/local1111
        # mlhgrsr:
        #     source: ./www222
        #     target: /var/www/local222
        # vcvxdse:
        #     source: ./www3333
        #     target: /var/www/local33
        # - local1
        # - local2
        # - local3
        # - local4
        # - local5
        - /var/www
nginx:
    install: '1'
    vhosts:
        local.dev:
            server_name: local.dev
            locations:
                nxvl_ygt11jvae0bq:
                    location: /
                    autoindex: on
                    index_files:
                        - index.html
                        - index.htm
                        - index.php
                        - /_h5ai/server/php/index.php
foo:
    bar: 12
    baz: 13
    foo: 14
